// =====================================================================
// 1. STATE & DATA (Modelo - Única fuente de verdad)
// =====================================================================

const DEFAULT_PORTALES = [
  { id: 1, categoria: 'Sistemas Internos / Externos', nombre: 'Carpeta Compartida', url: 'https://promesecal1.sharepoint.com/Documentos%20compartidos/Forms/AllItems.aspx', descripcion: 'Documentos compartidos en SharePoint', icono: 'folder' },
  { id: 2, categoria: 'Sistemas Internos / Externos', nombre: 'Correo Institucional', url: 'https://outlook.cloud.microsoft/mail/', descripcion: 'Acceso al correo @promesecal.gob.do', icono: 'mail' },
  { id: 3, categoria: 'Sistemas Internos / Externos', nombre: 'Dynamics 365', url: 'https://login.microsoftonline.com/0503b823-2203-40b2-9a56-7160e119e07e/oauth2/authorize?client_id=00000015-0000-0000-c000-000000000000&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3DAQAAANCMnd8BFdERjHoAwE_Cl-sBAAAA6bK6hrngzEq4UaIJLsKw-wAAAAACAAAAAAAQZgAAAAEAACAAAACOOUjCbLwCZDq6fxq0SRCpGn23MJ_zR2GccCFkvG2ntAAAAAAOgAAAAAIAACAAAABRA_yKCsw0gFE4KwoPTNAqnU_2SRx53EaFqvGg2xnCDEAAAAAjS7KIgv2i3ok4alZqF2qaJriDF26YzcxXOoWCUzLYtaOXLVQb8efGiCETgPxJ5ubonrKSmIoDA2PGKBxi1yH9QAAAAId9tSrRq8P3Hj_8ev5ChRRENN3XgLeVsBJ7-5OM5SIt8vMTpoxHAP-vVyZyJTuC86zy0eZRkkNnieqv6728MpI%26RedirectTo%3Dhttps%253A%252F%252Fpromesecal.operations.dynamics.com%252F&response_mode=form_post&nonce=639117679886090222.ZTkzYmM0YjAtOGFjMi00M2Q3LThjY2QtMjBkNGUzOWZiNGMyZjEzZjUxNjktMjZkMi00MDFjLTljMTUtMjYxMjc0NDMxZWFl&redirect_uri=https%3A%2F%2Fpromesecal.operations.dynamics.com%2F&max_age=86400&x-client-SKU=ID_NET472&x-client-ver=8.3.0.0', descripcion: 'Sistema de inventario y gestión ERP', icono: 'database' },
  { id: 4, categoria: 'Sistemas Internos / Externos', nombre: 'Portal de Farmacias del Pueblo', url: 'http://pfp.promesecal.gob.do/', descripcion: 'Portal de gestión de farmacias', icono: 'home' },
  { id: 5, categoria: 'Sistemas Internos / Externos', nombre: 'SGP — Sistema de Gestión de Pedidos', url: 'http://sgp.promesecal.gob.do/', descripcion: 'Seguimiento y gestión de pedidos', icono: 'package' },
  { id: 6, categoria: 'Sistemas Internos / Externos', nombre: 'Mesa de Ayuda', url: 'https://mesadeayuda.promesecal.gob.do/front/central.php', descripcion: 'Inventario y tickets DTIC (GLPI)', icono: 'headphones' },
  { id: 7, categoria: 'Sistemas Internos / Externos', nombre: 'Sistema de Horas Extras', url: 'http://horasextras.promesecal.gob.do/Login.php', descripcion: 'Registro y reportes de horas extras', icono: 'clock' },
  { id: 8, categoria: 'Sistemas Internos / Externos', nombre: 'Sistema de Registro de Pacientes POSFP', url: 'http://rp.promesecal.gob.do/login.aspx', descripcion: 'Registro de pacientes farmacias del pueblo', icono: 'clipboard-list' },
  
  { id: 9, categoria: 'Reportes de Operaciones', nombre: 'Recibo de Ingresos', url: 'http://promesevsap11/Reports/Pages/Report.aspx?ItemPath=/Reportes+Viejos/Tesoreria/GP+2018/Cuadre+de+Caja+%281%29', descripcion: 'Reporte de cuadre de caja', icono: 'file-text' },
  { id: 10, categoria: 'Reportes de Operaciones', nombre: 'Existencias por Lotes', url: 'http://reporte.promesecal.gob.do/Reports/Pages/Report.aspx?ItemPath=/Reportes+Viejos/Inventario/GP+2018/EXISTENCIA+POR+LOTE', descripcion: 'Inventario de insumos por lote', icono: 'layers' },

  { id: 11, categoria: 'Aplicaciones Externas (Gobierno)', nombre: 'MAP', url: 'https://map.gob.do/', descripcion: 'Portal del Ministerio de Administración Pública', icono: 'landmark' },
  { id: 12, categoria: 'Aplicaciones Externas (Gobierno)', nombre: 'Portal de Compras', url: 'https://comunidad.comprasdominicana.gob.do/STS/DGCP/Login.aspx', descripcion: 'Compras y Contrataciones Públicas (DGCP)', icono: 'shopping-cart' },
  { id: 13, categoria: 'Aplicaciones Externas (Gobierno)', nombre: 'SIGEF', url: 'https://www.transparenciafiscal.gob.do/web/guest', descripcion: 'Sistema de Gestión Financiera del Estado', icono: 'bar-chart' },
  { id: 14, categoria: 'Aplicaciones Externas (Gobierno)', nombre: 'Volante de Pago', url: 'https://map.gob.do/volantepago', descripcion: 'Consulta de volante de pago del personal', icono: 'credit-card' },
];

const RAW_DIR = `Ext.1050 · ELBYS ALFREDO PAULINO KING · ADMINISTRADOR DE REDES · DEPARTAMENTO DE OPERACIONES TICs
Ext.1503 · LINA PATRICIA MONTAÑO PEÑA DE FELIZ · ASESORA · DIRECCION GENERAL
Ext.1519 · JOCASTA ISABEL MEJIA TELLERIAS · AUXILIAR ADMINISTRATIVA · DEPARTAMENTO FISCALIZACION
Ext.1016 · ELBA DENEB TIO MARRERO · ASISTENTE DIRECCION GENERAL · DIRECCION GENERAL
Ext.1034 · YOLANDA T. MELGEN LOPEZ · ENCARGADO · DEPARTAMENTO ADMINISTRATIVO
Ext.1261 · SOCORRO RAMIREZ TURBI · SECRETARIA · ALMACEN MONUMENTAL
Ext.2201 · LUIS STALIN RODRIGUEZ RAMIREZ · COORDINADOR · ALMACEN MONUMENTAL
Ext.1621 · GISSELL ALTAGRACIA RODRIGUEZ CERDA · RECEPCIONISTA · ALMACEN REGION NORTE
Ext.1622 · YENNY MERCEDES CARABALLO DE GUZMAN · COORDINADORA ALMACEN REGION NORTE · ALMACEN REGION NORTE
Ext.1623 · ALFONSINA DE JESUS MENDEZ REYES · ANALISTA DE RECURSOS HUMANOS · ALMACEN REGION NORTE
Ext.1624 · YESSENIA ALTAGRACIA MINIER DE INOA · ANALISTA FARMACEUTICA · ALMACEN REGION NORTE
Ext.1625 · MADEYVI INMACULADA MADERA RODRIGUEZ · DIGITADOR I · ALMACEN REGION NORTE
Ext.1626 · YOVANINA CORONADO DE DOMINICI · ANALISTA · ALMACEN REGION NORTE
Ext.1627 · YEURI MANUEL CABRERA VASQUEZ · DIGITADOR I · ALMACEN REGION NORTE
Ext.1618 · LISSETTE NUNEZ · AUXILIAR ADMINISTRATIVO · ALMACEN REGION NORTE
Ext.1630 · ANA YLSA RODRIGUEZ DE CABRAL · FARMACEUTICO · ALMACEN REGION NORTE
Ext.1631 · JERSIN GUILLERMO PENA PEREZ · SUPERVISOR DE DISTRIBUCION · ALMACEN REGION NORTE
Ext.1602 · JUAN PABLO URENA GONZALEZ · ENCARGADO ALMACEN REGIONAL NORTE · ALMACEN REGIONAL NORTE
Ext.1629 · ROMEX DE LA CRUZ · FISCALIZADOR · ALMACEN REGIONAL NORTE
Ext.1611 · DANELYS MENDOZA · DIGITADORA · ALMACEN REGIONAL NORTE
Ext.3000 · AUDITORES EXTERNOS · AUDITORES EXTERNOS · AUDITORES EXTERNOS
Ext.1141 · AUDITORIA · AUDITORIA · CGR
Ext.1145 · AGUEDA GARCIA · AUDITORIA · CGR
Ext.1030 · JOSE HERRERA · CAMARERO · COMEDOR
Ext.1062 · CARLOS JOSE ALMANZAR RODRIGUEZ · TECNICO ADMINISTRATIVO · DEPARTAMENTO ADMINISTRATIVO
Ext.1137 · ALONDRA TERESA MORONTA ABREU · TECNICO ADMINISTRATIVO · DEPARTAMENTO ADMINISTRATIVO
Ext.1161 · CHARISMEL CASTILLO TAVERAS · TECNICO ADMINISTRATIVO · DEPARTAMENTO ADMINISTRATIVO
Ext.1061 · HECTOR HERNANDEZ · ENCARGADO · DEPARTAMENTO ADMINISTRATIVO
Ext.1032 · MERCEDES S. LAMA CASTRO · ENCARGADA · DEPARTAMENTO DE ACCESO A LA INFORMACION
Ext.1052 · DAYANA JORGE DE LEON · SECRETARIA · DEPARTAMENTO DE ACCESO A LA INFORMACION
Ext.1039 · FERNANDO MEDINA · ENCARGADO · DEPARTAMENTO DE ADMINISTRACION DEL SERVICIO TIC
Ext.1040 · FRANCISCO LIRIANO REYES · ADMINISTRADOR DE REDES · DEPARTAMENTO DE ADMINISTRACION DEL SERVICIO TIC
Ext.1051 · JUAN DANIEL TAVERAS FROMETA · SOPORTE TECNICO · DEPARTAMENTO DE ADMINISTRACION DEL SERVICIO TIC
Ext.1043 · FELIX MANUEL ROQUE BATISTA · ENCARGADO · DEPARTAMENTO DE OPERACIONES TICs
Ext.1066 · JEFFERSON ALMONTE · ENCARGADO · DEPARTAMENTO DE DESARROLLO E IMPLEMENTACION DE SISTEMAS
Ext.1139 · MANUELA MARIA JIMENEZ MOSCOSO · ENCARGADA · DEPARTAMENTO DE BIENESTAR SOCIAL
Ext.1213 · DOMINGA BAUTISTA PAYANO · TECNICO ADMINISTRATIVO · DEPARTAMENTO DE BIENESTAR SOCIAL
Ext.1216 · MARTHA JOHANNA RAMOS · AUXILIAR ADMINISTRATIVO · DEPARTAMENTO DE BIENESTAR SOCIAL
Ext.1190 · KERLAYNER CUEVAS MENDEZ DE PEREZ · ANALISTA · DEPARTAMENTO DE CALIDAD EN LA GESTION
Ext.1192 · SINEYDA MARGARITA GUZMAN · ENCARGADO · DEPARTAMENTO DE CALIDAD EN LA GESTION
Ext.1221 · YULEISY IDELISA RAMIREZ PERALTA · ANALISTA · DEPARTAMENTO DE COMPENSACION BENEFICIOS Y CAPACITACION
Ext.1227 · EDWIN EFRAIN MORA GONZALEZ · COORDINADOR · DEPARTAMENTO DE COMPENSACION BENEFICIOS Y CAPACITACION
Ext.1116 · YISSETE MEJIA VITTINI · ENCARGADA · DEPARTAMENTO DE COMPENSACION, BENEFICIOS Y CAPACITACION
Ext.1272 · ELIDA YOSAIRA FELIZ PEREZ · ASISTENTE ADMINISTRATIVA II · DEPARTAMENTO DE COMPENSACION, BENEFICIOS Y CAPACITACION
Ext.1291 · JUAN DIEGO LUNA · DIGITADOR · DEPARTAMENTO DE COMPENSACION, BENEFICIOS Y CAPACITACION
Ext.1151 · ISAURA SUERO MERAN · SECRETARIA · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1153 · KELVYN MANUEL ORTEGA TAPIA · COORDINADOR · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1154 · GERAL JOSE TAVERAS PARRA · ANALISTA · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1162 · ARISTIDES AMAURY SEGURA MEDINA · COORDINADOR · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1174 · ROBERT DANTE URBAEZ CUEVAS · ENCARGADO · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1176 · ELIZABETH DE LA CRUZ TELLERIA · AUXILIAR ADMINISTRATIVA · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1196 · MIGUELINA REYNOSO MORENO · ANALISTA · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1403 · ESMIRNALEE SANTANA ORTEGA · ANALISTA · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1402 · JEIDY LAURA MENDOZA FELIZ · AUXILIAR ADMINISTRATIVA · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1401 · ELIZABETH GERARDO DISLA · AUXILIAR · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1152 · MARIA DEL CARMEN MARTINEZ · ANALISTA · DEPARTAMENTO DE COMPRAS Y CONTRATACIONES
Ext.1231 · KATHERINE SHARINA GUERRA SERI · RELACIONISTA PUBLICO · DEPARTAMENTO DE COMUNICACIONES
Ext.1307 · ANYELO JAVIER MERCEDES · ENCARGADO · DEPARTAMENTO DE COMUNICACIONES
Ext.1308 · PAOLA MAIRENI VALDEZ CARRERAS · RELACIONISTA PUBLICO · DEPARTAMENTO DE COMUNICACIONES
Ext.1309 · JENNIFER DE DIOS · ANALISTA DE REDES SOCIALES · DEPARTAMENTO DE COMUNICACIONES
Ext.1310 · ANA SABRINA ROSARIO BISONO · ENCARGADA MULTIMEDIA Y CONTENIDO WEB · DEPARTAMENTO DE COMUNICACIONES
Ext.1311 · RAFAEL BIENVENIDO BORBON DE LEON · TECNICO DE AUDIOVISUALES · DEPARTAMENTO DE COMUNICACIONES
Ext.1260 · LUISA OLIVERO · ENCARGADO · DEPARTAMENTO DE ELABORACION DE DOCUMENTOS LEGALES
Ext.1163 · RUTH DELANIA TAVAREZ LUCIANO · TECNICO ADMINISTRATIVA · DEPARTAMENTO DE FISCALIZACION
Ext.1535 · EDDY ALFREDO HERNANDEZ PEREZ · ENCARGADO · DEPARTAMENTO DE FISCALIZACION
Ext.1183 · MARIA ISABEL NAUT ASTACIO · ENCARGADO · DEPARTAMENTO DE INGENIERIA E INFRAESTRUCTURA
Ext.1184 · CARMEN ALEXANDRA GARCIA DE LOS SANTOS · SECRETARIA · DEPARTAMENTO DE INGENIERIA E INFRAESTRUCTURA
Ext.1166 · LUIS BOYER MEDINA · ANALISTA LEGAL · DEPARTAMENTO DE LITIGIOS
Ext.1119 · MARLENE FERNANDEZ MERCEDES · TECNICO ADMINISTRATIVA · DEPARTAMENTO DE RECLUTAMIENTO, SELECCION Y EVALUACION DEL DESEMPENO
Ext.1215 · GISELA VERONICA MATIAS MENDEZ · ENCARGADA · DEPARTAMENTO DE RECLUTAMIENTO, SELECCION Y EVALUACION DEL DESEMPENO
Ext.1224 · GARYS MIGUEL PANIAGUA CANARIO · ANALISTA · DEPARTAMENTO DE RECLUTAMIENTO, SELECCION Y EVALUACION DEL DESEMPENO
Ext.1225 · OMAR FORTUNA TEJEDA · ANALISTA · DEPARTAMENTO DE REGISTRO CONTROL Y NOMINA
Ext.1270 · KARINA ELIZABETH PAREDES DE PEREZ · ANALISTA · DEPARTAMENTO DE REGISTRO, CONTROL Y NOMINA
Ext.1271 · LUCY CUEVAS SANTANA · ANALISTA · DEPARTAMENTO DE REGISTRO, CONTROL Y NOMINA
Ext.1108 · SOFIA ALTAGRACIA FRIAS HILARIO · ENCARGADA · DEPARTAMENTO DE REGISTRO, CONTROL Y NOMINAS
Ext.1247 · INDIRA MIOSOTIS DE JESUS · ASISTENTE ADMINISTRATIVA I · DEPARTAMENTO DE VIGILANCIA Y CONTROL DE CALIDAD
Ext.1249 · LEOCADIA MORONTA ESPINAL · ENCARGADA · DEPARTAMENTO DE VIGILANCIA Y CONTROL DE CALIDAD
Ext.1035 · HAMLET SAMAEL ALMANZAR JIMENEZ · DIRECTOR · DIRECCION DE TICs
Ext.1041 · ANYERI ANDREINA VIGAY · AUXILIAR ADMINISTRATIVO · DIRECCION DE TICs
Ext.1083 · ARELIS JULISSA JIMENEZ LORA · AUXILIAR ADMINISTRATIVA · DIRECCION DE TRAMITES Y SERVICIOS PARA LA SALUD
Ext.1086 · ROSANNA MARIOBY SARMIENTO GONZALEZ · ANALISTA · DIRECCION DE TRAMITES Y SERVICIOS PARA LA SALUD
Ext.1087 · JUANA MARIA PUMAROL PENA · ENCARGADA · DIRECCION DE TRAMITES Y SERVICIOS PARA LA SALUD
Ext.1088 · MELODY MARIA MOTA CALDERON · AUXILIAR ADMINISTRATIVA · DIRECCION DE TRAMITES Y SERVICIOS PARA LA SALUD
Ext.1090 · JULISA NORBERTO ROSARIO · DIRECTORA · DIRECCION DE TRAMITES Y SERVICIOS PARA LA SALUD
Ext.1085 · MANUELA SUAREZ · FARMACEUTICA · DIRECCION DE TRAMITES Y SERVICIOS PARA LA SALUD
Ext.1011 · DILENNY MONTERO CABRERA · SECRETARIA · DIRECCION GENERAL
Ext.1110 · JOSE LUIS LOPEZ PEREZ · DIRECTOR GENERAL · DIRECCION GENERAL
Ext.1111 · MICTOR EMILIO FERNANDEZ DE LA CRUZ · ASESOR · DIRECCION GENERAL
Ext.1285 · SANTOS GERVACIO SANCHEZ · ASISTENTE · DIRECCION GENERAL
Ext.1306 · DORIS MAGDALENA GARCIA REYNA · COORDINADORA · DIRECCION GENERAL
Ext.1165 · HAROLIN YUNEIBIS PUJOLS PEREZ · TECNICO ADMINISTRATIVO · DIRECCION JURIDICA
Ext.1168 · ANA KATIUSKA RAMIREZ ROJAS · ABOGADA · DIRECCION JURIDICA
Ext.1169 · MODESTO ANTONIO BATISTA ZABALA · ANALISTA LEGAL · DIRECCION JURIDICA
Ext.1170 · CAROLYN PENN DE BRITO · ANALISTA LEGAL · DIRECCION JURIDICA
Ext.1256 · FRANCISCO VASQUEZ CONCEPCION · DIRECTOR JURIDICO · DIRECCION JURIDICA
Ext.1257 · JOSE ALBERTO DE LEON VALERIO · ANALISTA LEGAL · DIRECCION JURIDICA
Ext.1258 · MADELINE GOMEZ PANIAGUA · ANALISTA LEGAL · DIRECCION JURIDICA
Ext.1259 · DIGNORA CRISTINA RAMIREZ · ANALISTA LEGAL · DIRECCION JURIDICA
Ext.1152 · ELIZABETH GERARDO DISLA · ENCARGADA · DIVISION DE ADQUISICIONES INTERNACIONALES
Ext.1140 · INGRIS REYES · ENCARGADA DE CONTABILIDAD · DIVISION DE CONTABILIDAD
Ext.1146 · ROSA PORTES SANTANA DE MARTINEZ · CONTADORA · DIVISION DE CONTABILIDAD
Ext.1150 · YAFANNY ALBANIA MORA MARTINEZ · AUXILIAR DE CONTABILIDAD · DIVISION DE CONTABILIDAD
Ext.1188 · MARIA ALTAGRACIA FRIAS GERALDO · ENCARGADA · DIVISION DE CONTROL DE BIENES
Ext.1010 · MERY DE JESUS · SECRETARIA · DIV. DE DEVOLUCION Y DECOMISO INSUMOS PARA LA SALUD
Ext.1015 · PETRA ISABEL SANCHEZ JIMENEZ · ENCARGADA · DIVISION DE DEVOLUCION Y DECOMISO INSUMOS PARA LA SALUD
Ext.1250 · ANA RAQUEL DE LA CRUZ · ENCARGADA · DIVISION DE INSPECCION DE CALIDAD DE MEDICAMENTOS
Ext.1006 · ELENA MADURO JAZMIN · SECRETARIA · DIVISION DE LICITACIONES
Ext.1026 · BRENDA ALMONTE RIVERA · ENCARGADA · DIVISION DE LICITACIONES
Ext.1203 · KENCY JOEL CAMINERO GUTIERREZ · ASISTENTE ADMINISTRATIVO · DIVISION DE LICITACIONES
Ext.1205 · PAOLA SANTA FARIAS PACIANS · ASISTENTE ADMINISTRATIVA · DIVISION DE LICITACIONES
Ext.1185 · TEFI BATISTA · ENCARGADO · DIVISION DE MEJORA Y ACONDICIONAMIENTO FISICO
Ext.1112 · MARTIRES REYES PEREZ · SUPERVISOR DE MANTENIMIENTO · DIVISION DE MEJORA Y ACONDICIONAMIENTO FISICO
Ext.1405 · MARIA ISABEL NAUT ASTACIO · ENCARGADA · DIVISION DE OBRAS, CONSTRUCCIONES Y SERVICIOS
Ext.1143 · JESUSCITA FELIZ DE MARTINEZ · ENCARGADO · DIVISION DE PRESUPUESTO
Ext.1262 · YUBEIRY DEL CARMEN RODRIGUEZ BAUTISTA · SECRETARIA · DIVISION DE RECEPCION DE IPS
Ext.1298 · MILCIADES DE LA CRUZ ENCARNACION · ENCARGADO · DIVISION DE SERVICIOS GENERALES
Ext.1070 · MARIA CRISTINA PAULA PRADO ACOSTA · ENCARGADA · DIVISION DE TESORERIA
Ext.1202 · ADALKIRA ALTAGRACIA DE LA ROSA JAVIER · SECRETARIA · DIVISION DE TESORERIA
Ext.1115 · KARINY JOHANNA NUNEZ PEGUERO · TECNICO ADMINISTRATIVO · DIVISION DE TRANSPORTACION
Ext.1241 · PEDRO COSS MENDEZ · ENCARGADO · DIVISION DE TRANSPORTACION
Ext.1096 · SERGIO JUNIOR BAEZ MATOS · DIGITADOR I · DIVISION RECEPCION DE INSUMOS PARA LA SALUD
Ext.1620 · STARLIN FELIPE TORIBIO · SOPORTE TECNICO · DTIC SANTIAGO
Ext.1218 · LUIS MANUEL PENA FELIZ · DIRECTOR DE RECURSOS HUMANOS · DIRECCION DE RECURSOS HUMANOS
Ext.1001 · RECEPCION 1ER NIVEL · RECEPCIONISTA · RECEPCION
Ext.1003 · RECEPCION 2DO NIVEL · RECEPCIONISTA · RECEPCION
Ext.1104 · SALON DE REUNIONES · SALON DE REUNIONES · SALON DE REUNIONES
Ext.1031 · KETTY GRISERT PEREZ SANTANA · TECNICO ADMINISTRATIVO · SECCION DE ALMACEN Y SUMINISTRO
Ext.1033 · JUNIOR ALBERTO VASQUEZ SOLANO · AUXILIAR DE ALMACEN · SECCION DE ALMACEN Y SUMINISTRO
Ext.1060 · JULIO CESAR BELTRE · ENCARGADO · SECCION DE ARCHIVO Y CORRESPONDENCIA
Ext.1091 · JOSE DEL CARMEN URENA FERREIRA · AUXILIAR CONTABILIDAD · SECCION DE CUENTAS POR COBRAR
Ext.1148 · JOHANNY MARGARITA RODRIGUEZ DE JESUS · ENCARGADA · SECCION DE CUENTAS POR COBRAR
Ext.1144 · ROCIO ALTAGRACIA ROSARIO DE AGUERO · ENCARGADA · SECCION DE CUENTAS POR PAGAR
Ext.1071 · ALVIC JOEL FRIAS GIL · ASISTENTE ADMINISTRATIVO · SECCION DE INGRESOS
Ext.1078 · XIOMARA ALTAGRACIA POZO MENDEZ · ENCARGADA · SECCION DE INGRESOS
Ext.1079 · GISELL ALFONSINA GUERRERO JUMA · SECRETARIA · SECCION DE INGRESOS
Ext.1187 · MANUEL EMILIO FLORIAN MENDEZ · ENCARGADO · SECCION DE INVENTARIO DE INSUMOS PARA LA SALUD
Ext.1277 · JEFFREY PEREZ · ENCARGADO · SEGURIDAD MILITAR
Ext.1007 · CARLOS ALBERTO PADILLA DURAN · SUB DIRECTOR · SUB DIRECCION
Ext.1008 · FRANCIA JULISSA CONCEPCION · ASISTENTE · SUB DIRECCION
Ext.1009 · ANDREA CANDIDA DIFO MARTE · SUB DIRECTORA · SUB DIRECCION
Ext.1048 · DIEGO BALBUENA ACOSTA · SUB DIRECTOR · SUB DIRECCION
Ext.1049 · ELIZABETH URENA JIMENEZ · AUXILIAR ADMINISTRATIVO · SUB DIRECCION
Ext.1064 · LUIS FRANCISCO LIZARDO GUZMAN · SUB DIRECTOR · SUB DIRECCION
Ext.1113 · MARIELA VALDEZ MATOS · SECRETARIA · SUB DIRECCION
Ext.1120 · KATTY ZUHEYLI PIMENTEL FERREIRA · SECRETARIA · SUB DIRECCION
Ext.1136 · CARMEN ILEANA DE LA ROSA BELTRE · ASISTENTE ADMINISTRATIVA I · SUB DIRECCION
Ext.1016 · AUDITORIA · AUDITORIA · UNIDAD DE AUDITORIA CGR`;

const DEFAULT_DIRECTORIO = RAW_DIR.trim().split('\n').filter(Boolean).map((line, idx) => {
  const parts = line.split('·').map(s => s.trim().replace(/\u00a0/g, ' '));
  const ext = parts[0] || '';
  const nombre = parts[1] || 'Usuario ' + idx;
  const cargo = parts[2] || 'Sin Cargo';
  const depto = parts[3] || 'Desconocido';
  
  const names = nombre.split(' ');
  const fname = names[0] ? names[0].toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '') : '';
  const lname = names.length > 1 ? names[names.length-1].toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '') : '';
  const correo = `${lname}.${fname}@promesecal.gob.do`;
  
  return { id: idx+1, nombre, cargo, departamento: depto, extension: ext, correo };
});

const DEFAULT_NOMENCLATURAS = [
  { id: 1, departamento: 'DIRECCIÓN GENERAL', nomenclatura: 'SCCDIRGRALPC01', usuario: 'Adolfo Perez' },
  { id: 2, departamento: 'DEPARTAMENTO JURIDICO', nomenclatura: 'SCDCDEPJURIPC01', usuario: 'Sin usuario' },
  { id: 3, departamento: 'TECNOLOGIA DE LA INFORMACION', nomenclatura: 'SCDIVASTIPC01', usuario: 'Luis Vargas' },
];

const DEFAULT_NOTICIAS = [
  { id: 1, titulo: 'Jornada de Vacunación contra la Influenza 2026', autor: 'Gestión Humana', fecha: '14 Abr 2026', imagen: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=300&q=80' },
  { id: 2, titulo: 'Actualización del sistema Dynamics 365 completada exitosamente', autor: 'DTIC', fecha: '12 Abr 2026', imagen: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=300&q=80' },
  { id: 3, titulo: 'Inauguración de nueva Farmacia del Pueblo en Santiago', autor: 'Dirección General', fecha: '10 Abr 2026', imagen: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=300&q=80' }
];

let feriados = [];
let directorio = (typeof LDAP_DATA !== 'undefined') ? [...LDAP_DATA] : [...DEFAULT_DIRECTORIO];
let nomenclaturas = [...DEFAULT_NOMENCLATURAS];
let portales = [...DEFAULT_PORTALES];
let noticias = [...DEFAULT_NOTICIAS];

try {
  const sDir = localStorage.getItem('promese_directorio'); if(sDir) directorio = JSON.parse(sDir);
  const sNom = localStorage.getItem('promese_nomenclaturas'); if(sNom) nomenclaturas = JSON.parse(sNom);
  const sPor = localStorage.getItem('promese_portales'); if(sPor) portales = JSON.parse(sPor);
  const sNot = localStorage.getItem('promese_noticias'); if(sNot) noticias = JSON.parse(sNot);
} catch(e) { console.log('Error parseando localStorage, usando defaults', e); }

let dirPage = 1;
let nomPage = 1;
let adminLoggedIn = false;

// Roles de Admin Hub
// 'it'   → acceso total
// 'rrhh' → Noticias + Menú del Día + Desvinculaciones
const ADMIN_PASSWORDS = {
  it: 'dtic2025',
  rrhh: 'rrhh2025'
};
let adminRole = null;

// Calendar state
let calYear = new Date().getFullYear();
let calMonth = new Date().getMonth();

function saveData() {
  localStorage.setItem('promese_directorio', JSON.stringify(directorio));
  localStorage.setItem('promese_nomenclaturas', JSON.stringify(nomenclaturas));
  localStorage.setItem('promese_portales', JSON.stringify(portales));
  localStorage.setItem('promese_noticias', JSON.stringify(noticias));
}

// ── Helpers: Menú del Día ──────────────────────────────────────────────
function getMenuDelDia() {
  try {
    const raw = localStorage.getItem('promese_menu_dia');
    return raw ? JSON.parse(raw) : null;
  } catch (e) {
    console.log('Error leyendo menú del día:', e);
    return null;
  }
}

function saveMenuDelDia(data) {
  localStorage.setItem('promese_menu_dia', JSON.stringify(data));
}

function clearMenuDelDia() {
  localStorage.removeItem('promese_menu_dia');
}

// ── Helpers: Desvinculaciones ───────────────────────────────────────────
function getDesvinculaciones() {
  try {
    const raw = localStorage.getItem('promese_desvinculaciones');
    return raw ? JSON.parse(raw) : [];
  } catch (e) {
    console.log('Error leyendo desvinculaciones:', e);
    return [];
  }
}

function saveDesvinculaciones(arr) {
  localStorage.setItem('promese_desvinculaciones', JSON.stringify(arr || []));
}
