# LDAP Sync Script for PROMESE/CAL Intranet
# Version: 1.1 (Modified to use Office as Extension and Telephone as Phone)

$LdapHost = "promese.promesecal.gob.do"
$LdapPort = "389"
$BaseDN = "DC=promese,DC=promesecal,DC=gob,DC=do"
$OutputFile = "..\js\ldap_data.js" # Path relative to script location

# Filter: Total Active users
$Filter = "(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"

Write-Host "Connecting to LDAP: $LdapHost ..." -ForegroundColor Cyan

try {
    $Searcher = [ADSISearcher]$Filter
    $Searcher.SearchRoot = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$LdapHost/$BaseDN")
    $Searcher.PageSize = 1000
    
    # Attributes to fetch
    $Searcher.PropertiesToLoad.Add("displayName") | Out-Null
    $Searcher.PropertiesToLoad.Add("title") | Out-Null
    $Searcher.PropertiesToLoad.Add("department") | Out-Null
    $Searcher.PropertiesToLoad.Add("physicalDeliveryOfficeName") | Out-Null # Oficina -> Extension
    $Searcher.PropertiesToLoad.Add("telephoneNumber") | Out-Null             # Telefono -> Telefono/Flota
    $Searcher.PropertiesToLoad.Add("mail") | Out-Null
    
    $Results = $Searcher.FindAll()
    $Employees = @()
    $IdCounter = 1

    Write-Host "Found $($Results.Count) employees. Processing..." -ForegroundColor Green

    foreach ($Result in $Results) {
        $Props = $Result.Properties
        
        $Employee = @{
            id = $IdCounter++
            nombre = if($Props.displayname) { $Props.displayname[0] } else { "" }
            cargo  = if($Props.title) { $Props.title[0] } else { "Colaborador" }
            departamento = if($Props.department) { $Props.department[0] } else { "Institucional" }
            extension = if($Props.physicaldeliveryofficename) { $Props.physicaldeliveryofficename[0] } else { "" }
            telefono = if($Props.telephonenumber) { $Props.telephonenumber[0] } else { "" }
            correo = if($Props.mail) { $Props.mail[0] } else { "" }
        }
        
        # Minor cleanups for extensions
        if ($Employee.extension -match "Ext\.") {
            # Keep
        } elseif ($Employee.extension -match "^\d+$") {
            $Employee.extension = "Ext." + $Employee.extension
        }

        $Employees += $Employee
    }

    # Convert to JSON and wrap in JS variable
    $JsonData = $Employees | ConvertTo-Json -Depth 5
    $JsContent = "// AUTO-GENERATED BY scripts/ldap_sync.ps1 - DO NOT EDIT MANUALLY`n"
    $JsContent += "const LDAP_DATA = " + $JsonData + ";"
    
    Set-Content -Path $OutputFile -Value $JsContent -Encoding UTF8
    
    Write-Host "Success! Generated $OutputFile with $($Employees.Count) records." -ForegroundColor Green

} catch {
    Write-Host "ERROR connecting to LDAP: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
